name: Android CI

on:
  push:
    branches: 
      - '*' 
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: run Data module unit tests
      run: ./gradlew data:testDebugUnitTest

    - name: run Client module unit tests
      run: ./gradlew nre-client:testDebugUnitTest

    - name: run app module unit tests
      run: ./gradlew app:testDebugUnitTest

    - name: Build Debug APK
      run: ./gradlew assembleDebug
