name: Android CI

on:
  push:
    branches: 
      - '*' 
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Run unit tests
    - name: Run Unit Tests
      run: ./gradlew data:testDebugUnitTest
    
    - name: Build with Gradle
      run: ./gradlew assembleDebug
